import { desc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { InsertUser, inferenceRuns, reviewActions, users } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch { _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId, name: user.name ?? null, email: user.email ?? null, loginMethod: user.loginMethod ?? null, lastSignedIn: user.lastSignedIn ?? new Date(), role: user.role ?? (user.openId === ENV.ownerOpenId ? "admin" : "user") }; await db.insert(users).values(values).onDuplicateKeyUpdate({ set: { name: values.name, email: values.email, loginMethod: values.loginMethod, lastSignedIn: values.lastSignedIn, role: values.role } }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function createInferenceRun(run: typeof inferenceRuns.$inferInsert) { const db = await getDb(); if (!db) return undefined; await db.insert(inferenceRuns).values(run); const result = await db.select().from(inferenceRuns).where(eq(inferenceRuns.publicId, run.publicId)).limit(1); return result[0]; }
export async function listInferenceRuns() { const db = await getDb(); if (!db) return []; return db.select().from(inferenceRuns).orderBy(desc(inferenceRuns.createdAt)).limit(100); }
export async function reviewInferenceRun(publicId: string, action: "approve" | "reject" | "annotate", annotation?: string, reviewerName?: string) { const db = await getDb(); if (!db) return undefined; const existing = await db.select().from(inferenceRuns).where(eq(inferenceRuns.publicId, publicId)).limit(1); const run = existing[0]; if (!run) return undefined; await db.insert(reviewActions).values({ inferenceRunId: run.id, action, annotation: annotation ?? null, reviewerName: reviewerName ?? null }); if (action !== "annotate") await db.update(inferenceRuns).set({ reviewStatus: action === "approve" ? "approved" : "rejected" }).where(eq(inferenceRuns.publicId, publicId)); return (await db.select().from(inferenceRuns).where(eq(inferenceRuns.publicId, publicId)).limit(1))[0]; }
